### ISSUE TITLE
LTRCCIF predictProb cannot allocate vector size of ..

### ISSUE THREAD

**Issue by petchpanu** [weichiyao/TimeVaryingData_LTRCforests#4]
Hi Weichi Yao,

Thanks for providing very great packages. I'm trying to use the predictProb function to find OOB errors with the parameter OOB = True. However, I got an error cannot allocate vector size of 587 Gb. The dataset I'm using has almost 1 million observations with 20 features. I understand that this probably occurs due to a large number of rows. Is it possible that I could loop through each subject to get each OOB error? Or any other way that I could get OOB errors?

Thank you in advance.

**Comment by weichiyao** [comment]
Hi there,

May I ask, are you trying to find OOB errors for each potential mtry value?
Maybe you would consider computing the K-fold cross validation error (i.e.
to train on (K-1) folds and test on the rest)? Please let me know if this
may help or I did not understand your question correctly!

Best,
Weichi

Thanks,
Weichi

**Comment by petchpanu** [comment]
Thank you for your fast reply! Yes, I'm trying to tune mtry and ntree value. Are you suggesting that I should do k-fold cross-validation then calculate the Brier score (or other metrics) between train and test set to find the best set of parameters?

Thank you very much.
Panu

**Comment by petchpanu** [comment]
Hi Weichi Yao,

Thank you for your reply. I have tried with mtry = 2 and I have no problem during training. I think I with k-fold cross-validation as you suggested to see if the problem still arises.

Thank you,
Panu
